### ISSUE TITLE
Custom completion handler

### ISSUE THREAD

**Issue by lukasbalaz** [Unity-Technologies/com.unity.ads.ios-support#1]
https://github.com/Unity-Technologies/com.unity.ads.ios-support/blob/34430c67801ea8735494a23f5689d93a81b11c8a/com.unity.ads.ios-support/Runtime/Plugins/iOS/TrackingAuthorizationManager.m#L43-L50

From this code, I assume there is currently no way to pass a custom completion handler when requesting authorization. I don't have enough experience with Objective-C to write a PR myself but it would be greatly appreciated if somebody added this feature. Thanks! :)

**Comment by LarsBlaabjerg** [comment]
It at least needs the ability to tell the difference between a non-supported platform, and not having completed the request yet.
As it is, we cannot know if we should wait for the state to change or not.

**Comment by AndreasMLarsen** [comment]
@lukasbalaz I've added a PR that adds a callback that you can pass when calling _RequestAuthorizationTracking_

**Comment by TanGrumser** [comment]
The callback method pretty much covers all use cases but as @LarsBlaabjerg said, i also believe that this package should  contain a method for checking if the OS version supports the ATT dialog.

**Comment by wagenheimer** [comment]
Unity released this package and then abandoned it! That is very sad!

 ATTrackingStatusBinding.RequestAuthorizationTracking(); is not working on a new build for me and I don't have means to find out what is wrong. It simples does not show the popup and does not show any message or error on Xcode.

It should at least approve the Pull Requests and release new versions.

**Comment by wagenheimer** [comment]
I found the cause of my problem. 
NSUserTrackingUsageDescription was missing on XCode.

**Comment by AndreasMLarsen** [comment]
[PR#2](https://github.com/Unity-Technologies/com.unity.ads.ios-support/pull/2) will add a completion handler and fix this issue. I can't request a reviewer or link the issue but maybe @UnitySteven can help out with that.

**Comment by vita-unity** [comment]
1.2.0 release includes support for RequestTrackingAuthorization callback.
