### ISSUE TITLE
App tracking transparancy popup not showing on unity 2022 LTS

### ISSUE THREAD

**Issue by TrusharRadadiya** [Unity-Technologies/com.unity.ads.ios-support#20]
I test this in two different LTS versions 2022.3.0f1 and 2022.3.4f1 but not getting the popup on testing. Unfortunately, I had to use the 2021 LTS version.

**Comment by MrBoggart** [comment]
I'm having the same issue in Unity 2022.3.14f1. It was working good in 2021.3.21f1 but we needed to upgrade.
