### ISSUE TITLE
Wrong method name with updateConversionValue selector

### ISSUE THREAD

**Issue by jannekaisgg** [Unity-Technologies/com.unity.ads.ios-support#3]
In SkAdNetworkManager updateConversionValue method the selector name **updateConversonValue:** is wrong. It should be **updateConversionValue:** instead.

Noticed this as all callbacks we received had conversion value of 0.

**Comment by IvyKun** [comment]
Please could someone update this? iOS 14.5 might be released tomorrow and everyone needs to have this ready...

**Comment by kristofgiber** [comment]
Agreed! It's odd that iOS 14.5 has been already released, the whole world is busy with the hurdles of App Tracking Transparency to reduce damages but Unity hasn't even made an official video tutorial or not even a forum post on how to get that ATT framework show properly in Unity projects. And even after ATT release was postponed by 6 months which would have been plenty of time for them to write up a clear step-by-step tutorial of their own (without the need for 3rd party plug-ins and blogs).

**Comment by UnitySteven** [comment]
This should be addressed in the 1.0.0 release that went live yesterday.  Please reopen this issue if continue to see any issues.
