### ISSUE TITLE
[Feature Request] Automatically add NSUserTrackingUsageDescription key into info.plist

### ISSUE THREAD

**Issue by kuoliangkwong** [Unity-Technologies/com.unity.ads.ios-support#5]
Feature Request:
Automatically add `NSUserTrackingUsageDescription` key into `info.plist` file when building the app.

Reasons: 
1. To make it easier when building a new Xcode project from Unity from fresh instead of going through same post-build steps for new build
2. Some Unity developers don't have knowledge on how Xcode works. Adding this feature could reduce the learning curve.

**Comment by kuoliangkwong** [comment]
Found out there's PostProcessBuild in Unity to add key in info.plist for custom build [https://forum.unity.com/threads/how-can-you-add-items-to-the-xcode-project-targets-info-plist-using-the-xcodeapi.330574/#post-2143867](url). Still prefer to have an option that does it automatically without writing a custom build script

**Comment by acareyup** [comment]
It is already mentioned on [iOS 14 technical integration guide](https://unityads.unity3d.com/help/monetization/ios14) how to implement this feature on your own.

**Comment by habibieamrullah** [comment]
You definitely must get your hand dirty with Xcode if you are building for iOS, don't think you can run away from it.

**Comment by vita-unity** [comment]
You can do it with PostProcessBuild script , see example in the [integration guide](https://unityads.unity3d.com/help/monetization/ios14) under Displaying an ATT permission request -> Configuring a user tracking description.
