### ISSUE TITLE
[Documentation Error] - Add NSUsageTrackingDescription

### ISSUE THREAD

**Issue by sourcetreehugger** [Unity-Technologies/com.unity.ads.ios-support#6]
Just tried the plugin today. The import via the package manager went well and the sample scene is nice to get started. However, there is one huge issue with documentation: 

**Nowhere is mentioned that you have to add NSUsageTrackingDescription to your info.plist.**

Without it, the native prompt doesnt event show in the demo scene. Please add this ASAP to your docs as this is a time waster for sure! Or at least provide a post-build script with a generic description to inject this automatically in your info.plist

Tested on:
iPad pro iOS 4th Gen
iOS 15.1
Built with Unity 2019.4.14f1
iOS 14 Advertising Support plugin 1.0.0

**Comment by vlsim** [comment]
This information is available in the documentation with a sample script to add it automatically (under Configuring a user tracking description):
https://unityads.unity3d.com/help/monetization/ios14

But I agree, this info should be visible in the readme repo as can be easily overlooked.
