### ISSUE TITLE
[Documentation Error] - Provide instructions for not showing the Unity popup in iOS version <14.X

### ISSUE THREAD

**Issue by sourcetreehugger** [Unity-Technologies/com.unity.ads.ios-support#7]
On iOS 14.X devices, the native prompt is showing up after clicking on the 'next' button in the imported sample scene provided by the package manager. However, when testing the exact same sample scene on an iOS version that is lower than 14, the Unity prompt to allow ad tracking is showing up every time since this iOS version does not support app tracking.

This can handled more gracefully by checking the iOS version in the plugin by adding a method:

`bool isAdTrackingSupported = ATTrackingStatusBinding.GetIfTrackingSupported();`

or by returning another enum value

`if(status == ATTrackingStatusBinding.AuthorizationTrackingStatus.NOT_SUPPORTED)
{
// TODO don't show the Unity popup
}`

Right now I'm working around this issue by checking the iOS version with 

`float systemVersion = float.Parse(UnityEngine.iOS.Device.systemVersion);`

I can imagine that many developers don't know that this plugin behaves like this on iOS versions lower than 14.X

Tested on:
iPhone 6
iOS 12.4.8
Built with Unity 2019.4.17f1 on xCode 12.4
iOS 14 Advertising Support 1.0.0 package installed via package manager

**Comment by jasontrask** [comment]
Thanks for this, I've got a small tweak to add though.

The `float.Parse` call doesn't like incremental versions like 15.0.1 and results in a **FormatException**.

Parsing the version string into a System.Version object first solves this:

    Version ver = Version.Parse(UnityEngine.iOS.Device.systemVersion);
    if (ver.Major >= 14)
    {
        //iOS 14+
    }

**Comment by vita-unity** [comment]
this has been fixed in 1.2.0 release. thanks!
